listen=YES
listen_ipv6=NO

# Sem acesso anônimo — requer credenciais
anonymous_enable=NO
local_enable=YES
write_enable=NO

# Chroot — usuário fica preso no próprio home
chroot_local_user=YES
allow_writeable_chroot=YES

# Modo passivo — necessário para Docker
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30010

# vsftpd precisa do IP real do host para modo passivo
# Isso é sobrescrito pelo setup.sh em runtime
pasv_address=192.168.0.12

local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
