listen=YES
listen_ipv6=NO

anonymous_enable=YES
no_anon_password=NO
local_enable=NO
write_enable=NO
anon_root=/srv/ftp

hide_ids=YES
dirlist_enable=YES
download_enable=YES
xferlog_enable=YES
use_localtime=YES

secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd

# Modo passivo para funcionar de forma previsível pelo FileZilla em localhost.
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30010
pasv_address=127.0.0.1
