services:
  pf-ctf:
    build:
      context: ./challenge
    container_name: pf-ctf
    ports:
      - "21:21"
      - "2222:22"
      - "30000-30010:30000-30010"
    restart: unless-stopped