services:
  machine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: machine
    hostname: R-E-P-O
    restart: unless-stopped
    ports:
      - "22:22"     # SSH
      - "21:21"     # FTP
      - "30000-30010:30000-30010"   # FTP DATA PASSIVE MODE
    attach: false
  web:
    build:
      context: reposerver
      dockerfile: nginx.Dockerfile
    container_name: web
    restart: unless-stopped
    depends_on:
      - back
    ports:
      - "80:80"
    volumes:
      - ./reposerver/nginxconfig/default.conf:/etc/nginx/conf.d/default.conf
      - ./reposerver/nginxconfig/nginx.conf:/etc/nginx/nginx.conf
      - ./reposerver/nginxconfig/mime.types:/etc/nginx/mime.types
      - ./reposerver/web:/var/www/html
    attach: false
  back:
    build:
      context: repo-backend
      dockerfile: Dockerfile
    container_name: back
    restart: unless-stopped
    ports:
      - "3000:3000"
    attach: false

